### ISSUE TITLE
Exit status 3221225620

### ISSUE THREAD

**Issue by artuuro** [EmirAzaiez/SilkroadSecurityJS#1]
Receiving this error while trying to parse packets from one side to another:
`npm ERR! Exit status 3221225620`

**Comment by EmirAzaiez** [comment]
Can you give me an exemple ? Then I can reproduce this problem

**Comment by artuuro** [comment]
@EmirAzaiez I've figured it out - ends up I had to stick to the pattern you showed me some time ago with the setTimeout loop. 
This was happening when I tried to pass one socket context into another and then calling the silkroadsecurity to parse the packets.
